# Generated by Django 3.2.9 on 2022-02-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='country',
            new_name='job',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mobile',
        ),
    ]
